services:
  tsdsbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    expose:
      - 3333
    environment:
      - PORT=3333
    networks:
      - app-network

  tsdsfrontend:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - tsdsbackend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge