FROM nginx:alpine

# Copy nginx config
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Copy frontend static files
COPY frontend/index.html /usr/share/nginx/html/
COPY frontend/config.docker.js /usr/share/nginx/html/config.js

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
